language: python
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install codecov
  - pip install flake8
install:
  - pip install . # install package
script: 
  - flake8 demo
  - flake8 setup.py
  - pytest --cov=demo # run tests
after_success:
  - codecov # submit coverage
