language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
services:
  - docker
before_install:
  - python --version
  - docker --version
  - pip install -U pip
  - pip install codecov
  - pip install tox-travis
install:
  - pip install . # install package
  - docker build -t tdd-demo .
script: 
  - tox -e flake8
  - tox -e pylint
  - tox -e docker
  - tox
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tdd_demo/
