language: python
matrix:
  include:
    - name: "Docker build"
      services: docker
      python: 3.7
      env: TOXENV=docker
      before_install: 
        - docker --version
        - pip install -U pip
        - pip install tox-travis
      install: docker build -t tdd-demo .
      script: tox -e $TOXENV
    - name: "Python 3.5"
      python: 3.5
      env: TOXENV=flake8,pylint,py35
    - name: "Python 3.6"
      python: 3.6
      env: TOXENV=flake8,pylint,py36
    - name: "Python 3.7"
      python: 3.7
      env: TOXENV=flake8,pylint,py37
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
  - pip install tox-travis
install:
  - pip install . # install package
script: 
  - tox -e $TOXENV
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tdd_demo/
