language: python
sudo: false
python:
  - 3.5
  - 3.6
  - 3.7
services:
  - docker
before_install:
  - python --version
  - docker --version
  - pip install -U pip
  - pip install flake8
  - pip install pylint
  - pip install -U pytest pytest-cov
  - pip install codecov
  - pip install tox-travis
install:
  - pip install . # install package
  - docker build -t tdd-demo .
script: 
  - tox
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tdd_demo/
