language: python
matrix:
  include:
    - name: "Python 3.5"
      python: 3.5
      env: TOXENV=py35
    - name: "Python 3.6"
      python: 3.6
      env: TOXENV=py36
    - name: "Python 3.7"
      python: 3.7
      env: TOXENV=py37
    - name: "Docker build"
      python: 3.7
      env: TOXENV=docker
services:
  - docker
before_install:
  - python --version
  - docker --version
  - pip install -U pip
  - pip install codecov
  - pip install tox-travis
install:
  - pip install . # install package
  - docker build -t tdd-demo .
script: 
  - tox -e flake8,pylint,$TOXENV
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tdd_demo/
